version: "3"
services:
  frontend:
    build: .
    ports:
      - "5000:5000"
    command: npm start
    environment:
      - SKIP_PREFLIGHT_CHECK:true
      - PORT:4200
      - HOST=0.0.0.0
      - REACT_APP_BACKEND_URL=http://192.168.55.14:3000

  backend:
    privileged: true
    build: ./backend/
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/src/backend
      - /src/backend/node_modules/
    command: /bin/sh -c 'node start.js & npm run start'
    depends_on:
      - mongodb
    environment:
      MONGO_DB: "mongodb://mongodb/irrigation"

  mongodb:
    image: mongo:3.6.23
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27018:27017"